services:
  app:
    image: hifrodo/jmmarket-app:v1
    restart: unless-stopped
    container_name: jmmarket-app
    depends_on:
      db-svc:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - jmmarket-net

  db-svc:
    image: hifrodo/jmmarket-db:v1
    restart: unless-stopped
    container_name: db-svc
    environment:
      MYSQL_DATABASE: jm_market
      MYSQL_USER: jm_user
      MYSQL_PASSWORD: jm_password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - jmmarket-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot_password --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - jmmarket-net

networks:
  jmmarket-net:
    driver: bridge

volumes:
  jmmarket-db-data:
